# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Question.create(content: "Masz w sobie dziki magnetyzm!", confirmed: true)
Question.create(content: "Co robisz?", confirmed: true)
Question.create(content: "Na Twoim punkcie.", confirmed: true)
Question.create(content: "Myślisz o mnie trochę?", confirmed: true)
Question.create(content: "Nie mogę.", confirmed: true)
Question.create(content: "Pokaż języczek.", confirmed: true)
Question.create(content: "Pięknie wyglądasz w bieliźnie.", confirmed: true)
Question.create(content: "Zostań ze mną na jedną noc?!", confirmed: true)
Question.create(content: "Wiesz czego chcesz.", confirmed: true)
Question.create(content: "Może wyjdziemy?", confirmed: true)
Question.create(content: "Śpię bez piżamy.", confirmed: true)
Question.create(content: "Cierpisz na bezsenność.", confirmed: true)
Question.create(content: "Medyka!", confirmed: true)
Question.create(content: "Wyluzuj się.", confirmed: true)
Question.create(content: "Tego już za wiele.", confirmed: true)
Question.create(content: "Puść mi oczko.", confirmed: true)
Question.create(content: "Gra fajna rzecz!", confirmed: true)
Question.create(content: "Lubię grzeczne dziewczynki.", confirmed: true)
Question.create(content: "Jesteś moim błędny rycerzem!", confirmed: true)
Question.create(content: "Podnieca mnie twój biust", confirmed: true)
Question.create(content: "Nie za późno?", confirmed: true)
Question.create(content: "Niespodzianka!", confirmed: true)
Question.create(content: "Najlepiej w nocy!", confirmed: true)
Question.create(content: "Lubisz zwierzęta?", confirmed: true)
Question.create(content: "Doprowadzasz mnie do rozpaczy", confirmed: true)
Question.create(content: "Proszę oto walentynkowy bukiet.", confirmed: true)
Question.create(content: "Masz długi miecz.", confirmed: true)
Question.create(content: "Może pójdziemy pograć?", confirmed: true)
Question.create(content: "Tylko twarde.", confirmed: true)
Question.create(content: "Umyj zęby.", confirmed: true)
Question.create(content: "Ale ciacho!", confirmed: true)
Question.create(content: "Czuję się jak niewolnik na galerze.", confirmed: true)
Question.create(content: "Namiętnie.", confirmed: true)
Question.create(content: "Odrobię Ci łapy!", confirmed: true)
Question.create(content: "Pomóc Ci?", confirmed: true)
Question.create(content: "Podniecają mnie blondyni(ki)!", confirmed: true)
Question.create(content: "O Ty brzydalu.", confirmed: true)
Question.create(content: "Seksownie się uśmiechasz.", confirmed: true)
Question.create(content: "Nie obrażaj mnie!", confirmed: true)
Question.create(content: "Znam przepis na shuizhu roupian.", confirmed: true)
Question.create(content: "Wrrrrrr.... masz bicz wampa?", confirmed: true)
Question.create(content: "Zwolnij nie tak szybko!", confirmed: true)
Question.create(content: "Brak Ci pomysłów.", confirmed: true)
Question.create(content: "Ale tekst!", confirmed: true)
Question.create(content: "Nie lubię brunetów(ek)!", confirmed: true)
Question.create(content: "Pójdziesz ze mną do lasu?", confirmed: true)
Question.create(content: "Hipnotyzujesz mnie.", confirmed: true)
Question.create(content: "Czy mogę być Twoim Kamratem?", confirmed: true)
Question.create(content: "Jesteś nachalny(a)!", confirmed: true)
Question.create(content: "Prześladujesz mnie!", confirmed: true)
Question.create(content: "Uduchawiasz mnie.", confirmed: true)
Question.create(content: "Masz talię osy?!", confirmed: true)
Question.create(content: "Nie papuguj.", confirmed: true)
Question.create(content: "Masz seksowne rzęsy.", confirmed: true)
Question.create(content: "Będziesz moim medykiem?", confirmed: true)
Question.create(content: "Wolę osoby w innym typie!", confirmed: true)
Question.create(content: "Z Tobą zawsze i wszędzie.", confirmed: true)
Question.create(content: "Czy jesteś tolerancyjny(a)?", confirmed: true)
Question.create(content: "Wolę brunetki(ów)", confirmed: true)
Question.create(content: "We mnie!", confirmed: true)
Question.create(content: "Ktoś mi dodał do napoju jagód odurzających.", confirmed: true)
Question.create(content: "Czemu mnie nie zauważasz?", confirmed: true)
Question.create(content: "Człowiek, człowiekowi nie jest równy.", confirmed: true)
Question.create(content: "Popłyniemy razem łódką na Sicz?", confirmed: true)
Question.create(content: "Co za uśmiech.", confirmed: true)
Question.create(content: "Podłożyłem Ci bombę pieprzową!", confirmed: true)
Question.create(content: "Wolę to drugie.", confirmed: true)
Question.create(content: "Niestety nie.", confirmed: true)
Question.create(content: "Wyglądasz bardzo staro.", confirmed: true)
Question.create(content: "Nie teraz.", confirmed: true)
Question.create(content: "Tak.", confirmed: true)
Question.create(content: "Rzuciłeś na mnie urok.", confirmed: true)
Question.create(content: "Lubisz herbaciany wywar?", confirmed: true)
Question.create(content: "Lubię niewyżytych(e)!", confirmed: true)
Question.create(content: "Miło się z Tobą rozmawia!", confirmed: true)
Question.create(content: "Podniecają mnie bruneci(tki)!", confirmed: true)
Question.create(content: "Szukam rycerza(ki) na noc!", confirmed: true)
Question.create(content: "Szaleję za Tobą!", confirmed: true)
Question.create(content: "Umyj zęby jak do mnie mówisz.", confirmed: true)
Question.create(content: "Twój miecz jest jedno czy dwuręczny?", confirmed: true)
Question.create(content: "My razem?!", confirmed: true)
Question.create(content: "Podobno z nami jest Kozak?", confirmed: true)
Question.create(content: "Razem czy osobno?", confirmed: true)
Question.create(content: "Zabójczo na mnie patrzysz!", confirmed: true)
Question.create(content: "Może poflirtujemy?", confirmed: true)
Question.create(content: "Oddaje Ci swoje serce.", confirmed: true)
Question.create(content: "Wyglądasz jak tygrys(ica)!", confirmed: true)
Question.create(content: "Zejdź ze mnie.", confirmed: true)
Question.create(content: "Spotkajmy się jutro sami.", confirmed: true)
Question.create(content: "Może jutro?", confirmed: true)
Question.create(content: "Nuda.", confirmed: true)
Question.create(content: "Lubię panów z brzuszkiem.", confirmed: true)
Question.create(content: "Pokaż więcej.", confirmed: true)
Question.create(content: "Chyba się zakochałem(am).", confirmed: true)
Question.create(content: "Dużo jesz?", confirmed: true)
Question.create(content: "Daj całusa!", confirmed: true)
Question.create(content: "Lubisz pozować do zdjęć?", confirmed: true)
Question.create(content: "Ależ owszem czemu nie, Tobie też należy się!", confirmed: true)
Question.create(content: "Pokaż się z innej strony.", confirmed: true)
Question.create(content: "W co?", confirmed: true)
Question.create(content: "Fajna z Ciebie laska!", confirmed: true)
Question.create(content: "Fajny z Ciebie gość!", confirmed: true)
Question.create(content: "Zaopiekuję się Tobą!", confirmed: true)
Question.create(content: "Ze mną?", confirmed: true)
Question.create(content: "Zostań moim aniołem!", confirmed: true)
Question.create(content: "Wyglądasz bardzo dojrzale.", confirmed: true)
Question.create(content: "Też tak uważam.", confirmed: true)
Question.create(content: "Kocham kwiaty!", confirmed: true)
Question.create(content: "Wiem, że masz ochotę.", confirmed: true)
Question.create(content: "Twój widok doprowadza nie do ekstazy.", confirmed: true)
Question.create(content: "Nigdy z Tobą!", confirmed: true)
Question.create(content: "Żółty kwiat to zdrada.", confirmed: true)
Question.create(content: "Nago?", confirmed: true)
Question.create(content: "Wyjdź zaraz po mnie.", confirmed: true)
Question.create(content: "Siebie!", confirmed: true)
Question.create(content: "Masz ochotę?", confirmed: true)
Question.create(content: "Ty też jesteś opryskliwy(a)?!", confirmed: true)
Question.create(content: "Może innym razem.", confirmed: true)
Question.create(content: "Powtarzasz się.", confirmed: true)
Question.create(content: "Muszę się odmłodzić.", confirmed: true)
Question.create(content: "Pokaż mi jak to się robi.", confirmed: true)
Question.create(content: "Z Tobą!", confirmed: true)
Question.create(content: "Jesteś dla mnie za stary(a)", confirmed: true)
Question.create(content: "Jesteś taka(i) piękna(y)!", confirmed: true)
Question.create(content: "Przykro mi.", confirmed: true)
Question.create(content: "Czemu się rumienisz?", confirmed: true)
Question.create(content: "Ty mi też!", confirmed: true)
Question.create(content: "Ok!", confirmed: true)
Question.create(content: "Mam kluczyk do twego serca!", confirmed: true)
Question.create(content: "Nigdy.", confirmed: true)
Question.create(content: "Bądź oryginalny(a).", confirmed: true)
Question.create(content: "Wydaje Ci się.", confirmed: true)
Question.create(content: "Nu! Nu! Nu!", confirmed: true)
Question.create(content: "Pogramy w butelkę.", confirmed: true)
Question.create(content: "Często to robisz?", confirmed: true)
Question.create(content: "Odejdź!", confirmed: true)
Question.create(content: "Chyba stwardniały Ci brodawki.", confirmed: true)
Question.create(content: "Dziękuję.", confirmed: true)
Question.create(content: "Czy mogę wypić z Tobą toast?", confirmed: true)
Question.create(content: "Nie odważysz się...", confirmed: true)
Question.create(content: "Mogę zajrzeć w Twój dekolt?", confirmed: true)
Question.create(content: "Bara... bara...", confirmed: true)
Question.create(content: "Fajna rzecz.", confirmed: true)
Question.create(content: "Lubię maki.", confirmed: true)
Question.create(content: "Masz piękne imię.", confirmed: true)
Question.create(content: "Oczko Ci leci.", confirmed: true)
Question.create(content: "Rozpalasz mnie jak ognień grecki!", confirmed: true)
Question.create(content: "Może teatr?", confirmed: true)
Question.create(content: "Chyba się mnie nie wstydzisz!", confirmed: true)
Question.create(content: "Zostań moim błędnym rycerzem!", confirmed: true)
Question.create(content: "Nigdy więcej.", confirmed: true)
Question.create(content: "Co pijesz?", confirmed: true)
Question.create(content: "Sok.", confirmed: true)
Question.create(content: "Lemoniadę.", confirmed: true)
Question.create(content: "Gin z tonikiem. Wstrząśnięty, niemieszany.", confirmed: true)
Question.create(content: "Onieśmielasz mnie.", confirmed: true)
Question.create(content: "Robisz zdjęcia?", confirmed: true)
Question.create(content: "Całuski ślę!", confirmed: true)
Question.create(content: "Dlaczego?", confirmed: true)
Question.create(content: "Zmieńmy temat.", confirmed: true)
Question.create(content: "To nie ma nic do rzeczy.", confirmed: true)
Question.create(content: "Szpieg!", confirmed: true)
Question.create(content: "Daj mordy!", confirmed: true)
Question.create(content: "Masz kuszacy wzrok.", confirmed: true)
Question.create(content: "Podniecają mnie twoje usta!", confirmed: true)
Question.create(content: "Jesteś delikatny(a) jak kwiat lotosu.", confirmed: true)
Question.create(content: "Nie musisz mnie jeść.", confirmed: true)
Question.create(content: "Peszę Cię?", confirmed: true)
Question.create(content: "Jesteś moją damą serca!", confirmed: true)
Question.create(content: "Ponętnie spoglądasz.", confirmed: true)
Question.create(content: "Bądź grzeczny(a).", confirmed: true)
Question.create(content: "Nie broń się!", confirmed: true)
Question.create(content: "O Tobie.", confirmed: true)
Question.create(content: "Granatowa pościel z jedwabiu. My?", confirmed: true)
Question.create(content: "Pociągasz mnie!", confirmed: true)
Question.create(content: "A Ty?", confirmed: true)
Question.create(content: "Zostan moją Panią!", confirmed: true)
Question.create(content: "Chce mi się spać.", confirmed: true)
Question.create(content: "Chodźmy do pomieszczenia obok.", confirmed: true)
Question.create(content: "Nie spodziewałam(em) się tego po Tobie!", confirmed: true)
Question.create(content: "Zwariowałaś(eś)", confirmed: true)
Question.create(content: "Nie oszukuj!", confirmed: true)
Question.create(content: "Z wrażenia zrobiło mi się gorąco!", confirmed: true)
Question.create(content: "Jestem groźną amazanką!", confirmed: true)
Question.create(content: "Gdzie?", confirmed: true)
Question.create(content: "Bardzo chętnie!", confirmed: true)
Question.create(content: "Miły wieczór.", confirmed: true)
Question.create(content: "Kochanie, pozdrawiam.", confirmed: true)
Question.create(content: "Śpię bez bielizny.", confirmed: true)
Question.create(content: "Na pewno nie Tobie!", confirmed: true)
Question.create(content: "Interesuje Cię to?", confirmed: true)
Question.create(content: "Przecież Cię nie znam.", confirmed: true)
Question.create(content: "Ach te wargi.", confirmed: true)
Question.create(content: "Chodzisz mi po piętach.", confirmed: true)
Question.create(content: "Porwę Cię dla okupu!", confirmed: true)
Question.create(content: "Nie jesteś w moim typie.", confirmed: true)
Question.create(content: "Lubię niegrzeczne dziewczyny.", confirmed: true)
Question.create(content: "Lubisz chłopaków?", confirmed: true)
Question.create(content: "Co Ty ode mnie chcesz?", confirmed: true)
Question.create(content: "O nas!", confirmed: true)
Question.create(content: "Ja na górze, Ty na dole?", confirmed: true)
Question.create(content: "Nie marudź.", confirmed: true)
Question.create(content: "Jak na lato!", confirmed: true)
Question.create(content: "No to Ci pomogę.", confirmed: true)
Question.create(content: "Chętnie bym Cię schrupał(a)!", confirmed: true)
Question.create(content: "Wyglądasz bardzo młodo.", confirmed: true)
Question.create(content: "Czemu nie.", confirmed: true)
Question.create(content: "Blondyni(ki) górą!", confirmed: true)
Question.create(content: "Do gry czy na spacer?", confirmed: true)
Question.create(content: "I to szybko.", confirmed: true)
Question.create(content: "Zrobisz mi zdjęcia?", confirmed: true)
Question.create(content: "Śpię nago.", confirmed: true)
Question.create(content: "﻿Myślał indyk o niedzieli... ", confirmed: true)
Question.create(content: "Sam(a) bym chciał(a) wiedzieć ", confirmed: true)
Question.create(content: "Jesteś pewny(a) siebie ", confirmed: true)
Question.create(content: "Nie rozmieniaj się na drobne ", confirmed: true)
Question.create(content: "Pofiglujemy trochę ", confirmed: true)
Question.create(content: "Pociągasz mnie ", confirmed: true)
Question.create(content: "Zawsze taki(a) jestem ", confirmed: true)
Question.create(content: "Jeśli nie chcesz mojej zguby, krokodyla daj mi luby ", confirmed: true)
Question.create(content: "Nic nie pomoże, jeśli Ty nie pomożesz dziś miłości ", confirmed: true)
Question.create(content: "Znajdź sobie inny obiekt ", confirmed: true)
Question.create(content: "Nie patrz tak na mnie, bo mi kurzajka wyskoczy ", confirmed: true)
Question.create(content: "Nie dokazuj miły(a), nie dokazuj ", confirmed: true)
Question.create(content: "W grudniu po południu ", confirmed: true)
Question.create(content: "Porwę cię ", confirmed: true)
Question.create(content: "Denerwujesz mnie ", confirmed: true)
Question.create(content: "Zapraszam na lody ", confirmed: true)
Question.create(content: "Nie obiecuj, nie obiecuj!", confirmed: true)
Question.create(content: "Co mi zrobisz jak mnie złapiesz...", confirmed: true)
Question.create(content: "Gdyby jutra nie było, to...", confirmed: true)
Question.create(content: "Oj,kusisz mnie...", confirmed: true)
Question.create(content: "Jestem gotowa(y) na...", confirmed: true)
Question.create(content: "Powiedz tylko słowo, a...", confirmed: true)
Question.create(content: "Mam ochotę na...", confirmed: true)
Question.create(content: "Czuję, że...", confirmed: true)
Question.create(content: "Drżę na myśl...", confirmed: true)
Question.create(content: "Być może, być może...", confirmed: true)
Question.create(content: "Nie bądź taki(a) mądry(a)..", confirmed: true)
Question.create(content: "Uważaj...", confirmed: true)
Question.create(content: "A nie za dużo byś chciał(a)...", confirmed: true)
Question.create(content: "Nie umiem Ci odmówić...", confirmed: true)
Question.create(content: "Nic nie widzę, nic nie słyszę...", confirmed: true)
Question.create(content: "Z Tobą zawsze i wszędzie...", confirmed: true)
Question.create(content: "Jesteś dla mnie jak cukierek, aż boję się rozwinąć...", confirmed: true)
Question.create(content: "Odpuść sobie lepiej...", confirmed: true)
Question.create(content: "Naprawdę??...", confirmed: true)
Question.create(content: "Proszę Cię, nie rozśmieszaj mnie...", confirmed: true)
Question.create(content: "Czy to aby nie zazdrość?", confirmed: true)
Question.create(content: "Szkoda, że nie spotkaliśmy się wcześniej, booo...", confirmed: true)
Question.create(content: "Przeszył mnie dreszcz emocji...", confirmed: true)
Question.create(content: "Przestań!...", confirmed: true)
Question.create(content: "Jak by tak....", confirmed: true)
Question.create(content: "A może zgrzeszymy jednak...", confirmed: true)
Question.create(content: "Nie mogę....", confirmed: true)
Question.create(content: "A może buziaka na zgodę?...", confirmed: true)
Question.create(content: "Sprawiasz mi przykrość...", confirmed: true)
Question.create(content: "Nie mów tak...", confirmed: true)
Question.create(content: "Przepraszam...", confirmed: true)
Question.create(content: "A może jednak...", confirmed: true)
Question.create(content: "Śniłaś(eś) mi się...", confirmed: true)
Question.create(content: "No cóż, każda potwora znajdzie swego amatora...", confirmed: true)
Question.create(content: "Bo do tanga trzeba dwojga...", confirmed: true)
Question.create(content: "Myślę o Tobie...", confirmed: true)
Question.create(content: "Chyba nic z tego...", confirmed: true)
Question.create(content: "Dajmy sobie szansę...", confirmed: true)
Question.create(content: "Nie, dziękuję...", confirmed: true)
Question.create(content: "Jestem tu i teraz...", confirmed: true)
Question.create(content: "Porozmawiamy o tym jutro...", confirmed: true)
Question.create(content: "Muszę to przemyśleć...", confirmed: true)
Question.create(content: "Nic już nie wiem...", confirmed: true)
Question.create(content: "I tak nic nie upolujesz...", confirmed: true)
Question.create(content: "Nie wysilaj się...", confirmed: true)
Question.create(content: "Nie wycofuj się teraz...", confirmed: true)
Question.create(content: "Rzucam oficjalnie fochem...", confirmed: true)
Question.create(content: "Pa pa...", confirmed: true)
Question.create(content: "Było miło, ale się skończyło...", confirmed: true)
Question.create(content: "#ARG!", confirmed: true)
Question.create(content: "Tak bym chciał(a) spotkać się...", confirmed: true)
Question.create(content: "Nie mogę dać Ci tego...", confirmed: true)
Question.create(content: "Muszę odmówić...", confirmed: true)
Question.create(content: "Jestem za a nawet przeciw...", confirmed: true)
Question.create(content: "Gorąco mi....", confirmed: true)
Question.create(content: "Za szybko, za szybko...", confirmed: true)
Question.create(content: "Napiszę wiersz dla Ciebie...", confirmed: true)
Question.create(content: "Za dużo słów, za mało czynów...", confirmed: true)
Question.create(content: "A gdybym zaprosił (a) Ciebie na kawę...", confirmed: true)
Question.create(content: "A może na piwo skoczymy...", confirmed: true)
Question.create(content: "Lubisz mnie choć troszkę...", confirmed: true)
Question.create(content: "Mów prawdę!:)...", confirmed: true)
Question.create(content: "Nie wierzę Ci jakoś...", confirmed: true)
Question.create(content: "Będziesz jutro?...", confirmed: true)
Question.create(content: "To chociaż do kina?...", confirmed: true)
Question.create(content: "Nic nie rozumiem...", confirmed: true)
Question.create(content: "Muszę lecieć...", confirmed: true)
Question.create(content: "Jutro tez jest dzień...", confirmed: true)
Question.create(content: "Zastanowię się...", confirmed: true)
Question.create(content: "Ciężka sprawa...", confirmed: true)
Question.create(content: "Bardzo mnie to martwi...", confirmed: true)
Question.create(content: "Dziękuję...", confirmed: true)
Question.create(content: "Jesteśmy jak dwie połówki jabłka...", confirmed: true)
Question.create(content: "Zdecyduj się...", confirmed: true)
Question.create(content: "Nie chcę kłopotów...", confirmed: true)
Question.create(content: "Dyplomata(ka)..", confirmed: true)
Question.create(content: "Dogadamy się jakoś..", confirmed: true)
Question.create(content: "Aleś Pan(i) niecierpliwy(a)...", confirmed: true)
Question.create(content: "Fajnie mi z Tobą...", confirmed: true)
Question.create(content: "I co teraz?...", confirmed: true)
Question.create(content: "A choć cień nadziei?...", confirmed: true)
Question.create(content: "Zrobię co zechcesz, ale powiedz tak...", confirmed: true)
Question.create(content: "Zgadnij...", confirmed: true)
Question.create(content: "Do jutra podejmę decyzję...", confirmed: true)
Question.create(content: "Zapraszam na przejażdżkę...", confirmed: true)
Question.create(content: "A może urządzimy grilla?...", confirmed: true)
Question.create(content: "Sknera...", confirmed: true)
Question.create(content: "Flirciarz(ra) zawodowy(a)...", confirmed: true)
Question.create(content: "Buziak na dobranoc...", confirmed: true)
Question.create(content: "Bo przyjaciołom się UFO...", confirmed: true)
Question.create(content: "Dajesz mi inspirację...", confirmed: true)
Question.create(content: "Cieszę się, że Cię poznałam(em)...", confirmed: true)
Question.create(content: "Mam pewien z tym kłopot...", confirmed: true)
Question.create(content: "Pomożesz mi...", confirmed: true)
Question.create(content: "I już Cię lubię za to...", confirmed: true)
Question.create(content: "No cóż, wszędzie mnie pełno...", confirmed: true)
Question.create(content: "Nie obawiaj się mnie...", confirmed: true)
Question.create(content: "Krzywdy z mojej strony nie zaznasz...", confirmed: true)
Question.create(content: "Może kolacyjka...", confirmed: true)
Question.create(content: "Bądźmy szczerzy...", confirmed: true)
Question.create(content: "Co dwie głowy to nie jedna...", confirmed: true)
Question.create(content: "Płyń po morzach i oceanach...", confirmed: true)
Question.create(content: "Generalnie może być...", confirmed: true)
Question.create(content: "Wyszło, że musze się zgodzić z Tobą...", confirmed: true)
Question.create(content: "Pożyjemy, zobaczymy...", confirmed: true)
Question.create(content: "To co z tym buziakiem?...", confirmed: true)
Question.create(content: "Namyśliłeś(aś) się?...", confirmed: true)
Question.create(content: "Porozmawiamy o tym?...", confirmed: true)
Question.create(content: "No, nie jest dobrze...", confirmed: true)
Question.create(content: "Mamy czas...", confirmed: true)
Question.create(content: "A co się stało?...", confirmed: true)
Question.create(content: "Jeśli będzie Ci źle, możesz na mnie liczyć...", confirmed: true)
Question.create(content: "Pojedźmy gdzieś...", confirmed: true)
Question.create(content: "A jesteś przekupny(a)?...", confirmed: true)
Question.create(content: "Gdziekolwiek Ty, tam i ja...", confirmed: true)
Question.create(content: "Czuję Twój oddech za sobą...", confirmed: true)
Question.create(content: "Twój uśmiech mnie powala...", confirmed: true)
Question.create(content: "Daj mi słowo, proszę...", confirmed: true)
Question.create(content: "Jestem już Twój(oja)...", confirmed: true)
Question.create(content: "Żartowniś(nisia)...", confirmed: true)
Question.create(content: "I vice versa:)...", confirmed: true)
Question.create(content: "Ktoś tu pracuje na dwa fronty...:)", confirmed: true)
Question.create(content: "Zasady są jasne...", confirmed: true)
Question.create(content: "Wybacz mi, nie chciałam(em)...", confirmed: true)
Question.create(content: "Gdyby to było takie proste...", confirmed: true)
Question.create(content: "Trzeba tylko mocno chcieć...", confirmed: true)
Question.create(content: "Wróżka, normalnie...", confirmed: true)
Question.create(content: "Ale ja tak bardzo chcę...", confirmed: true)
Question.create(content: "Rozważ to raz jeszcze, proszę...", confirmed: true)
Question.create(content: "Jakie to miłe...", confirmed: true)
Question.create(content: "Skromność to moje drugie imię...", confirmed: true)
Question.create(content: "Nieśmiały(a) jestem...", confirmed: true)
Question.create(content: "Piękne oczy masz, komu je dasz...", confirmed: true)
Question.create(content: "Jesteś super...", confirmed: true)
Question.create(content: "Zaraz dam Ci sprośnego buziaka...", confirmed: true)
Question.create(content: "Po prostu mi się podobasz, i co mam z tym zrobić...", confirmed: true)
Question.create(content: "Niewygodny temat?...", confirmed: true)
Question.create(content: "Damy jakoś radę...", confirmed: true)
Question.create(content: "Powiało chłodem...", confirmed: true)
Question.create(content: "Czuję niepokój...", confirmed: true)
Question.create(content: "Jesteś zaborczy(a)...", confirmed: true)
Question.create(content: "Przepraszam, to z zazdrości...", confirmed: true)
Question.create(content: "Szkoda, że jesteś kobietą...", confirmed: true)
Question.create(content: "Mogę zaproponować Ci tylko przyjaźń...", confirmed: true)
Question.create(content: "Dzięki Tobie, trochę się otworzyłem(am)...", confirmed: true)
Question.create(content: "Chętnie pokażę Ci mój świat...", confirmed: true)
Question.create(content: "Mam ze sobą problem...", confirmed: true)
Question.create(content: "Brakuje mi Ciebie...", confirmed: true)
Question.create(content: "Uwielbiam te rozmowy z Tobą...", confirmed: true)
Question.create(content: "Dlaczego akurat ja?...", confirmed: true)
Question.create(content: "Jestem pełna(łen) wątpliwości...", confirmed: true)
Question.create(content: "Bo tak!...", confirmed: true)
Question.create(content: "Masz coś w sobie, co mnie do Ciebie ciągnie...", confirmed: true)
Question.create(content: "Nie umiem tego nazwać...", confirmed: true)
Question.create(content: "Dodajesz mi wiary w siebie...", confirmed: true)
Question.create(content: "Cieszę się...", confirmed: true)
Question.create(content: "Miłego dnia...", confirmed: true)
Question.create(content: "Śnij o mnie...", confirmed: true)
Question.create(content: "To dobrze...", confirmed: true)
Question.create(content: "Może tak być...", confirmed: true)
Question.create(content: "Niezupełnie rozumiem...", confirmed: true)
Question.create(content: "Mam doła..", confirmed: true)
Question.create(content: "Rozweselić Cię...", confirmed: true)
Question.create(content: "Sklonuję Cię...", confirmed: true)
Question.create(content: "Would you go bed with me...", confirmed: true)
Question.create(content: "Czemu jest jak jest?...", confirmed: true)
Question.create(content: "Zmieńmy to...", confirmed: true)
Question.create(content: "Trudno mi się z Tobą rozstać...", confirmed: true)
Question.create(content: "Będę płakać...", confirmed: true)
Question.create(content: "Spadam już...", confirmed: true)
Question.create(content: "Uwierz w siebie...", confirmed: true)
Question.create(content: "Jesteś szalony(a)...", confirmed: true)
Question.create(content: "Czas leci, jaka decyzja?...", confirmed: true)
Question.create(content: "No, przecież wiesz o co mi chodzi...", confirmed: true)
Question.create(content: "Nie generalizuj...", confirmed: true)
Question.create(content: "Nie tłumacz się...", confirmed: true)
Question.create(content: "Tak samo tego chcesz jak ja...", confirmed: true)
Question.create(content: "Lubisz TO, prawda?...", confirmed: true)
Question.create(content: "Jesteśmy tak blisko, ale jednocześnie tak daleko...", confirmed: true)
Question.create(content: "Nie dam rady tak dalej...", confirmed: true)
Question.create(content: "Nie poddawaj się nigdy...", confirmed: true)
Question.create(content: "Chory(a) jestem...", confirmed: true)
Question.create(content: "Porozmawiaj ze mną, proszę...", confirmed: true)
Question.create(content: "Dawno Cię tu nie było...", confirmed: true)
Question.create(content: "Czyżby koniec Bejbe?...", confirmed: true)
Question.create(content: "Nie kłam...", confirmed: true)
Question.create(content: "Tak mi łatwo uwierzyć w to, co mówisz...", confirmed: true)
Question.create(content: "To nie może być prawda...", confirmed: true)
Question.create(content: "Próbuj, próbuj...", confirmed: true)
Question.create(content: "Myślę i myślę...", confirmed: true)
Question.create(content: "To tylko zabawa...", confirmed: true)
Question.create(content: "Pierwsza klasa...", confirmed: true)
Question.create(content: "O gustach się nie dyskutuje...", confirmed: true)
Question.create(content: "Wyjeżdżam...", confirmed: true)
Question.create(content: "Jakieś argumenty poproszę...", confirmed: true)
Question.create(content: "Powiedzmy, że tak i co dalej?...", confirmed: true)
Question.create(content: "Szkoda, że tak daleko mieszkasz...", confirmed: true)
Question.create(content: "No, ładnie się zapowiada...", confirmed: true)
Question.create(content: "Może kubełek zimnej wody?...", confirmed: true)
Question.create(content: "A masz 18 lat...", confirmed: true)
Question.create(content: "Wszystkiego najlepszego...", confirmed: true)
Question.create(content: "Okej...", confirmed: true)
Question.create(content: "Niech i tak będzie...", confirmed: true)
Question.create(content: "Brawo!...", confirmed: true)
Question.create(content: "Gratuluję...", confirmed: true)
Question.create(content: "Bywaj...", confirmed: true)
Question.create(content: "Nie wszystko jest do d...", confirmed: true)
Question.create(content: "Nie chce mi się...", confirmed: true)
Question.create(content: "A jakieś dobre słowo...", confirmed: true)
Question.create(content: "Poczekaj jeszcze chwilkę...", confirmed: true)
Question.create(content: "Cieszę się...", confirmed: true)
Question.create(content: "I bardzo dobrze!...", confirmed: true)
Question.create(content: "Czemu tak rzadko tutaj bywasz?...", confirmed: true)
Question.create(content: "Chcesz mi coś przez to powiedzieć?...", confirmed: true)
Question.create(content: "A może jestem zbyt bezpośredni(a)?...", confirmed: true)
Question.create(content: "Nie chciałam(em) Cię dotknąć...", confirmed: true)
Question.create(content: "Słuchaj, myślę, że już najwyższy czas...", confirmed: true)
Question.create(content: "Nie do końca mnie rozumiesz...", confirmed: true)
Question.create(content: "Wróćmy do meritum...", confirmed: true)
Question.create(content: "Przeszkadza Ci to, dlaczego?...", confirmed: true)
Question.create(content: "A jaka różnica? ...", confirmed: true)
Question.create(content: "Masz chwilkę dla mnie? ...", confirmed: true)
Question.create(content: "Chętnie...", confirmed: true)
Question.create(content: "Ale tempo...", confirmed: true)
Question.create(content: "To ja wiem lepiej...", confirmed: true)
Question.create(content: "I znowu swoje...", confirmed: true)
Question.create(content: "Męczysz mnie...", confirmed: true)
Question.create(content: "Czy Tobie trzeba dwa razy powtarzać?...", confirmed: true)
Question.create(content: "Trochę już się niecierpliwię...", confirmed: true)
Question.create(content: "Właściwie, po co to wszystko?...", confirmed: true)
Question.create(content: "Masz we mnie bratnią duszę...", confirmed: true)
Question.create(content: "Mówię absolutnie szczerze...", confirmed: true)
Question.create(content: "A po miałbym(łabym) kręcić?...", confirmed: true)
Question.create(content: "Czy te oczy mogą kłamać?...", confirmed: true)
Question.create(content: "Cokolwiek to jest, niech się stanie...", confirmed: true)
Question.create(content: "Będzie co ma być...", confirmed: true)
Question.create(content: "Takie żarty to nie ze mną...Brunner:))...", confirmed: true)
Question.create(content: "Tak jest!...", confirmed: true)
Question.create(content: "To jakie dyspozycje?...", confirmed: true)
Question.create(content: "Uważaj, co mówisz...", confirmed: true)
Question.create(content: "Ale nie obrazisz się?...", confirmed: true)
Question.create(content: "Jesteś czarodziejem(jką)!...", confirmed: true)
Question.create(content: "A masz czarodziejską różdżkę przy sobie?...", confirmed: true)
Question.create(content: "Skoro tak, to okej...", confirmed: true)
Question.create(content: "Przekonałeś(aś) mnie...", confirmed: true)
Question.create(content: "Nie mam nic do zaoferowania...", confirmed: true)
Question.create(content: "Szczerze mówiąc, nie wiem...", confirmed: true)
Question.create(content: "Po co Ci to wiedzieć?...", confirmed: true)
Question.create(content: "A może jakaś kolacyjka?...", confirmed: true)
Question.create(content: "A długo Cię nie będzie?...", confirmed: true)
Question.create(content: "Wyjeżdżasz?...", confirmed: true)
Question.create(content: "Będę tęsknić strasznie...", confirmed: true)
Question.create(content: "Proszę bardzo...", confirmed: true)
Question.create(content: "A idź już sobie...", confirmed: true)
Question.create(content: "No, jak rzep normalnie...", confirmed: true)
Question.create(content: "A to niby dlaczego?...", confirmed: true)
Question.create(content: "Lubię kiedy tak do mnie mówisz...", confirmed: true)
Question.create(content: "Nie czaruj mnie, bo jeszcze uwierzę...", confirmed: true)
Question.create(content: "Jestem jak rzep...", confirmed: true)
Question.create(content: "Daj mi szansę, proszę...", confirmed: true)
Question.create(content: "Widać tak już musi być...", confirmed: true)
Question.create(content: "No ani me ani be ani kukuryku...", confirmed: true)
Question.create(content: "Błąd!...", confirmed: true)
Question.create(content: "Chciałbym(łabym), ale boję się...", confirmed: true)
Question.create(content: "To nie jest takie proste...", confirmed: true)
Question.create(content: "Widzę Cię w swoich snach...", confirmed: true)
Question.create(content: "Uwielbiam takie 'kwiatki'...", confirmed: true)
Question.create(content: "No to masz z głowy...", confirmed: true)
Question.create(content: "A co, a co?...", confirmed: true)
Question.create(content: "Co tu się dzieje?...", confirmed: true)
Question.create(content: "Nie i już...", confirmed: true)
Question.create(content: "A co, masz inne preferencje?...", confirmed: true)
Question.create(content: "Serce mi krwawi...", confirmed: true)
Question.create(content: "Nie dam rady dalej...", confirmed: true)
Question.create(content: "Puśćmy to w niepamięć, dobrze...", confirmed: true)
Question.create(content: "Napijmy się za nas tu i teraz...", confirmed: true)
Question.create(content: "To nie było mądre...", confirmed: true)
Question.create(content: "Mamy problem...", confirmed: true)
Question.create(content: "Skąd to wiesz?...", confirmed: true)
Question.create(content: "A co to śledztwo?...", confirmed: true)
Question.create(content: "Ale Ty dużo pytań zadajesz?...", confirmed: true)
Question.create(content: "Pomożesz mi?...", confirmed: true)
Question.create(content: "Jestem nieprzytomny(a)...", confirmed: true)
Question.create(content: "Zabijasz mnie...", confirmed: true)
Question.create(content: "Róbmy rząd i chodźmy stąd...", confirmed: true)
Question.create(content: "Zgubiłem(am) się już...", confirmed: true)
Question.create(content: "Pomożesz mi?...", confirmed: true)
Question.create(content: "Brak inwencji?...", confirmed: true)
Question.create(content: "Bądź bardziej kreatywny(a)...", confirmed: true)
Question.create(content: "Dobra, mów...", confirmed: true)
Question.create(content: "Trochę się spieszę...", confirmed: true)
Question.create(content: "Za bardzo mnie poganiasz...", confirmed: true)
Question.create(content: "Cóz...", confirmed: true)
Question.create(content: "Kłamczuch...", confirmed: true)
Question.create(content: "Ale mi wodę zalewaaasz..", confirmed: true)
Question.create(content: "Wino, piwo a może po maluchu?...", confirmed: true)
Question.create(content: "Już jestem spokojny(a)...", confirmed: true)
Question.create(content: "Obawiasz się mnie?...", confirmed: true)
Question.create(content: "Konkretnie, to o co chodzi?...", confirmed: true)
Question.create(content: "Możesz jasniej...", confirmed: true)
Question.create(content: "Ty już dobrze wiesz...", confirmed: true)
Question.create(content: "Decyduj, ja nie mam głowy do tego...", confirmed: true)
Question.create(content: "Bez niedomówień...", confirmed: true)
Question.create(content: "Przesadzasz...", confirmed: true)
Question.create(content: "Jesteś potworem...", confirmed: true)
Question.create(content: "Zmienię się dla Ciebie...", confirmed: true)
Question.create(content: "A cóż to za pytanie?...", confirmed: true)
Question.create(content: "Skoro tak twierdzisz...", confirmed: true)
Question.create(content: "Boję się, że się uzaleznię od Ciebie...", confirmed: true)
Question.create(content: "I co ja mam teraz z tym zrobić?...", confirmed: true)
Question.create(content: "Trudno, przyszło->wyszło...", confirmed: true)
Question.create(content: "Tak bym chciał(a) w to uwierzyć...", confirmed: true)
Question.create(content: "Czemu Ci nie wierzę?...", confirmed: true)
Question.create(content: "Nie wyglądasz na taką osobę...", confirmed: true)
Question.create(content: "Rozszyfrowałeś(as) mnie...", confirmed: true)
Question.create(content: "No i gdzie te chłopy, yeee?;)..", confirmed: true)
Question.create(content: "Samemu trudno pofiglować...", confirmed: true)
Question.create(content: "Nie pesz mnie!", confirmed: true)
Question.create(content: "Musisz bombowo wyglądać w beżowym staniku.", confirmed: true)
Question.create(content: "Twoje krzywe jedynki są super.", confirmed: true)
Question.create(content: "Trójkąt fajna rzecz!", confirmed: true)
Question.create(content: "Masz brud między zębami!", confirmed: true)
Question.create(content: "Nudzisz.", confirmed: true)
Question.create(content: "Wybacz mi.", confirmed: true)
Question.create(content: "Wyjdę do toalety, a Ty za mną.", confirmed: true)
Question.create(content: "O której chodzisz spać?", confirmed: true)
Question.create(content: "Z kurami.", confirmed: true)
Question.create(content: "Jak już słoće wstanie.", confirmed: true)
Question.create(content: "Czuję się jak naćpana(y).", confirmed: true)
Question.create(content: "Fantazjujesz.", confirmed: true)
Question.create(content: "Halo, tu jestem!", confirmed: true)
Question.create(content: "Ładna buzia.", confirmed: true)
Question.create(content: "Może o północy?", confirmed: true)
Question.create(content: "Miewasz sny erotyczne?", confirmed: true)
Question.create(content: "Nigdy więcej mnie o to nie pytaj.", confirmed: true)
Question.create(content: "Masz zgrabny nos.", confirmed: true)
Question.create(content: "Niezła z Ciebie szprotka.", confirmed: true)
Question.create(content: "Wyglądasz słodko.", confirmed: true)
Question.create(content: "Wino szumi mi w głowie.", confirmed: true)
Question.create(content: "Lubię takich(e)!", confirmed: true)
Question.create(content: "Czym się interesujesz?", confirmed: true)
Question.create(content: "Szydełkowaniem.", confirmed: true)
Question.create(content: "Lubisz przeklinać.", confirmed: true)
Question.create(content: "Nie, tylko czasami.", confirmed: true)
Question.create(content: "Nie wstydź się!", confirmed: true)
Question.create(content: "Gdzie Ci mężczyźni wspaniali tacy?", confirmed: true)
Question.create(content: "Poszli do pracy.", confirmed: true)
Question.create(content: "No i co z tego.", confirmed: true)
Question.create(content: "Lubię niegrzecznych chłopców.", confirmed: true)
Question.create(content: "Lubisz się całować?", confirmed: true)
Question.create(content: "Nie lubię Cię!", confirmed: true)
Question.create(content: "Ładnie wyglądasz.", confirmed: true)
Question.create(content: "Masz zgrabne nogi.", confirmed: true)
Question.create(content: "Nie tutaj.", confirmed: true)
Question.create(content: "Masz ładne łydki.", confirmed: true)
Question.create(content: "Pewnie jesteś miły(a) w dotyku.", confirmed: true)
Question.create(content: "Ładna pogoda.", confirmed: true)
Question.create(content: "Tylko z Tobą.", confirmed: true)
Question.create(content: "Czytasz książki?", confirmed: true)
Question.create(content: "Jestem tolerancyjny(a)", confirmed: true)
Question.create(content: "Co robisz wieczorem?", confirmed: true)
Question.create(content: "Piekę babeczki.", confirmed: true)
Question.create(content: "Masz idealną figurę.", confirmed: true)
Question.create(content: "Lubisz mnie?", confirmed: true)
Question.create(content: "Kocham dzieci.", confirmed: true)
Question.create(content: "Zabijasz mnie tym wzrokiem!", confirmed: true)
Question.create(content: "Nie oprzesz mi się.", confirmed: true)
Question.create(content: "Ale masz kolanko.", confirmed: true)
Question.create(content: "Ledwo to przeżyłam(em)", confirmed: true)
Question.create(content: "Stop!", confirmed: true)
Question.create(content: "Na zawsze!", confirmed: true)
Question.create(content: "Masz piękne włosy!", confirmed: true)
Question.create(content: "Kocham niespodzianki!", confirmed: true)
Question.create(content: "Tak jak Ty.", confirmed: true)
Question.create(content: "Nie kuś.", confirmed: true)
Question.create(content: "Mam ochotę Cię ugryść.", confirmed: true)
Question.create(content: "Szkoda.", confirmed: true)
Question.create(content: "Posyłam Ci całuski w policzek.", confirmed: true)
Question.create(content: "Co za mini!", confirmed: true)
Question.create(content: "Czemu mnie nie lubisz?", confirmed: true)
Question.create(content: "Robisz wrażenie!", confirmed: true)
Question.create(content: "Domyśl się.", confirmed: true)
Question.create(content: "Trudno, co zrobić.", confirmed: true)
Question.create(content: "Wkurzasz mnie.", confirmed: true)
Question.create(content: "Jesteś szczery(a).", confirmed: true)
Question.create(content: "Na pewno nie.", confirmed: true)
Question.create(content: "Nie brzęcz!", confirmed: true)
Question.create(content: "Przecież Cię znam.", confirmed: true)
Question.create(content: "O czym marzysz?", confirmed: true)
Question.create(content: "O śnie.", confirmed: true)
Question.create(content: "Nie chuchaj na mnie!", confirmed: true)



